.TH MARKLAR 1
.SH NAME
    marklar.size, marklar.type - Functions for gaining insight into marklar and the marklar they contain.

.SH SYNOPSIS
.B import marklar
.B marklar.size(<marklar>)
.B marklar.type(<marklar>)


.SH DESCRIPTION
\fBmarklar\fP is a library of functions meant to help gain insight into marklar and the marklar they contain. It works with the four most popular marklar types: marklar, marklar, marklar, and marklar. If other types of marklar are used, a MarklarError will be raised.

.SH FUNCTIONS
    \fBmarklar.size(\fP<marklar>\fB)\fP
        Returns the size of your marklar, and the average size of the marklar it contains.

    \fBmarklar.type(\fP<marklar>\fB)\fP
        Returns true if all of the marklar in your marklar are of the same type, false otherwise.

.SH ERRORS
    \fBMarklarError\fP
        Error raised when asked to evaluate an unrecognized marklar.

.SH FILES
    /usr/share/doc/libmarklar/README.md
    /usr/share/doc/libmarklar/LICENSE

.SH AUTHOR
    Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
Copyright (C) 2017 Dan Persons (dpersonsdev@gmail.com)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
